services:
  - type: web
    name: birthday-surprise-website
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run preview
    envVars:
      - key: NODE_VERSION
        value: 18.0.0
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 